### ISSUE TITLE
Deployed,enabled ingress, trying to login but can't seem to know my username and password, can you help me ?

### ISSUE THREAD

**Issue by ahmeddrawy** [twuni/docker-registry.helm#16]

**Comment by canterberry** [comment]
Sounds like you may have an htpasswd issue.

The htpasswd value should be *the content of an htpasswd file* created using the `htpasswd` CLI tool (vs a path to a htpasswd file).

If that sounds like it may be the issue, and the above fixes it, hooray! If not, could you share some more detail on how you're configuring auth for your registry?

Either way, this reminds me the README isn't very clear on the htpasswd value, so I'll update that this evening.

**Comment by ahmeddrawy** [comment]
I already added the htpasswd content, i try `docker login <public ip - addresss from ingress> `, I have `ingress.enabled =true`

**Comment by ahmeddrawy** [comment]
Also i'd love to contribute so please tell me if you need any help

**Comment by milesand** [comment]
I seem to be having this issue too. I tried specifying the contents of htpasswd file in values.yaml, like this:
```
secret:
  htpasswd: "<contents of htpasswd>"
```

and this(trailing newline):
```
secret:
  htpasswd: |
    <contents of htpasswd>
```

In both cases, I can't sign in through browser's builtin prompt that pops up when I visit `<my registry domain>/v2/`.

Running `htpasswd -v` in a docker container shows that the username-password pair I'm entering is correct, and accessing the running pod shows that `/auth/htpasswd` is (apparently) identical to the htpasswd file in question. I'm pretty much lost here.

**Comment by milesand** [comment]
Upon further inspection, it appears the htpasswd file is actually a symlink to `/auth/..data/htpasswd`, where `/auth/..data` is also a symlink to another directory in `auth` whose name looks like some sort of datetime/timestamp. Unsure if this is related, but I'm noting it as it's not what I expected.

**Comment by milesand** [comment]
Never mind, I found out that htpasswd file had to be generated with `-B` flag (bcrypt) and it was missing. Now it works fine.

**Comment by stevek-pro** [comment]
Can someone please provide full explanation what to generate and what to put into the helm chart?
