### ISSUE TITLE
Persistence volume claim with longhorn not working

### ISSUE THREAD

**Issue by maconic** [twuni/docker-registry.helm#17]
I have tried to deploy the chart with a PVC on k3s with Rancher and Longhorn, but keep getting the error:

500 Internal Server Error
POST https://docker.host/v2/app/blobs/uploads/
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"filesystem","Enclosed":{"Op":"mkdir","Path":"/var/lib/registry/docker/registry/v2/repositories/app/_uploads/29ef60bf-e509-4832-a2eb-d60ec8d3e58e","Err":28}}}]}

**Comment by styk-tv** [comment]
confirmed with chart `1.11.0`

```
persistentvolume/pvc-cc3a169d-bb5c-4d5a-87e2-6f59572bb2   30Gi       RWO            Retain           Bound    registry/registry-docker-registry                 longhorn                2m14s
```

accomplished with `1.1.0`
```
persistence:
  enabled: true
  size: 30Gi
  storageClass: 'longhorn'
```
