### ISSUE TITLE
Chart ingress not working in latest k8s

### ISSUE THREAD

**Issue by ElArtista** [twuni/docker-registry.helm#33]
According to the k8s deprecation guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
```
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.
Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.
```
Fix should be applied here: https://github.com/twuni/docker-registry.helm/blob/b321438d4e383b2d2335c09d5d2d879a46683bb7/templates/ingress.yaml#L5
And probably here:
https://github.com/twuni/docker-registry.helm/blob/b321438d4e383b2d2335c09d5d2d879a46683bb7/templates/ingress.yaml#L28

**Comment by canterberry** [comment]
Fixed in v2.0.0.
