### ISSUE TITLE
Add support for custom envFrom secretRef's and configMapRef's

### ISSUE THREAD

**Issue by Raboo** [twuni/docker-registry.helm#36]
Hi,

Would it be possible to add custom `envFrom` support in the future?

Background, I am running rook-ceph (operator for running distributed storage ceph).
It has a ObjectBucketClaim that can create s3 buckets. The OBC in turn creates a ConfigMap and a Secret that contains following keys BUCKET_REGION, BUCKET_HOST, BUCKET_PORT, BUCKET_NAME, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. In order for me to use these with this helm chart I need to first apply the OBC. Then open the configmap and secret and copy the values from the keys and insert them for this helm chart values and then install the helm chart. Makes it impossible for me to automate.

If you could make it so I can add additional `envFrom[].secretRef` and `envFrom[].configMapRef` into the values that are applied to the pod container specs. Then I could easily use the above mentioned auto-generated keys as values like so:

```
secrets.s3.accessKey=$(AWS_ACCESS_KEY_ID)
secrets.s3.secretKey=$(AWS_SECRET_ACCESS_KEY)
s3.region=$(BUCKET_REGION)
s3.regionEndpoint=$(BUCKET_HOST)
s3.bucket=$(BUCKET_NAME)
```

Thanks!

**Comment by klausenbusk** [comment]
It was added after you created the issue (https://github.com/twuni/docker-registry.helm/pull/35) and a new release hasn't been released (yet).

**Comment by Raboo** [comment]
@canterberry can you push v1.14.0 to the helm repo so I can test pr #35?

**Comment by Raboo** [comment]
For some reason the variable interpolation is not working for some reason, in normal cases it should work like this:

```bash
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name # or "status.hostIP" or "spec.nodeName" etc
    - name: INTERPOLATION
      value: abc-$(HOSTNAME)
    command: ['sh', '-c', 'sleep 3600']
  restartPolicy: Never
$ kubectl apply -f pod.yaml
pod/busybox created
```

```bash
$ kubectl exec -it busybox -- sh -c 'echo $INTERPOLATION'
abc-busybox
$ kubectl delete pod busybox
pod "busybox" deleted
```

For the registry pods it simply looks like this
```bash
$ kubectl exec -it registry-c46cf8b8c-6m54d -- sh -c 'echo $REGISTRY_STORAGE_S3_SECRETKEY'
$(AWS_SECRET_ACCESS_KEY)
```

I expected the output to be my actual s3 secret key.
Any idea on what is wrong?

**Comment by darox** [comment]
So the S3 integration should definitely support other S3 provider than AWS. I'm having issues with Minio:
`2b6b3509ddbc: Pushing [==================================================>]  44.08MB
791274611ac9: Layer already exists 
dc365698f1f2: Layer already exists 
636159d907db: Pushing [==================================================>]  8.871MB
485115e86f04: Layer already exists 
30f3545290f2: Retrying in 5 seconds 
7fcd2600f5ad: Pushing [=======================>                           ]  8.582MB/18.47MB
8f56c3340629: Pushing [====================>                              ]    216MB/528.4MB
ba6e5ff31f23: Pushing [============================================>      ]  135.3MB/151.9MB
9f9f651e9303: Waiting 
0b3c02b5d746: Waiting 
62a747bf1719: Waiting 
received unexpected HTTP status: 500 Internal Server Error`

**Comment by Raboo** [comment]
Using other S3 than AWS works. The part that doesn't work for me is to reuse the already existing secret keys I got.

**Comment by darox** [comment]
I got it running with Minio, but layers are partly failing with:
```
2b6b3509ddbc: Pushing [==================================================>]  44.08MB
791274611ac9: Pushed 
dc365698f1f2: Pushed 
636159d907db: Pushing [==================================================>]  8.871MB
485115e86f04: Pushed 
30f3545290f2: Pushing [==================================================>]  56.94MB
7fcd2600f5ad: Pushing [==================================================>]  19.04MB
8f56c3340629: Pushing [====================================>              ]  388.9MB/528.4MB
ba6e5ff31f23: Pushing [====================>                              ]  63.28MB/151.9MB
9f9f651e9303: Retrying in 11 seconds 
0b3c02b5d746: Retrying in 5 seconds 
62a747bf1719: Waiting 
received unexpected HTTP status: 500 Internal Server Error
```

**Comment by Raboo** [comment]
@darox I expect that to be an separate issue, what does it have to do with adding support for custom envFrom that are interpolated?

**Comment by joshsizer** [comment]
Closing this issue as the extraEnvVars was implemented and there has been no new activity in quite some time.
