### ISSUE TITLE
Release 1.15.0 not published

### ISSUE THREAD

**Issue by MrSimonEmms** [twuni/docker-registry.helm#43]
I saw that the release was published this morning (thanks), but doesn't appear that it's been published to https://helm.twun.io/index.yaml  for usage.

Is this correct or has a job failed somewhere?

**Comment by MrSimonEmms** [comment]
Helm is respectfully disagreeing. When I run `helm search repo twuni/docker-registry`, I get this:

```shell
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                     
twuni/docker-registry	1.14.0       	2.7.1      	A Helm chart for Docker Registry
```

I'd expect to see the version at `1.15.0`.

FYI, I've also run `helm repo add twuni https://helm.twun.io` and `helm repo update` immediately before it. There's also no 1.15.0 release in  https://helm.twun.io/index.yaml

**Comment by canterberry** [comment]
I have inspected that file personally on an independent device and it does indeed have an entry for 1.15.0.

**Comment by MrSimonEmms** [comment]
That's very weird. The commands I ran whilst writing the previous ticket is now showing, even the `curl` - it was even breaking in our CI/CD pipelines, so it wasn't just my device.

Whatever's happened, it's working for me now. Thanks

**Comment by canterberry** [comment]
It may have been the Cloudfront distribution. I create a cache invalidation after each release to try and ensure subsequent requests return the latest, but I've been doing that for `/`.

I'll start specifically triggering invalidations for `/index.yaml` instead, which should, in theory, be treated as higher priority and result in near-immediate cache invalidations.
