### ISSUE TITLE
Feature request: Add sidecar containers

### ISSUE THREAD

**Issue by aslubsky** [twuni/docker-registry.helm#46]
We need to run sidecar container with garbage collector runned by cron.
I've prepared PR https://github.com/twuni/docker-registry.helm/pull/45

**Comment by aslubsky** [comment]
Hey guys, any news about this? @canterberry can you apply or reject this PR?

**Comment by canterberry** [comment]
@aslubsky We just got PR #68 merged, which includes the ability to enable a CronJob for garbage collection. That's available now in v2.2.0. For that reason, I'm going to mark this as resolved and close PR #45.

**Comment by aslubsky** [comment]
Awesome, thanks!
